### ISSUE TITLE
Does it work or tested on 0.12.0 ?

### ISSUE THREAD

**Issue by fusionx1** [ucb-ist-drupal/SiteClone#13]
$  terminus site clone  --source-site=pdp7 --target-site-prefix=clone --target-site-suffix=01 

Fatal error: Class 'Terminus\Collections\Sites' not found in /Users/fusionx1/terminus/plugins/SiteClone/Commands/SiteClone.php on line 42
fusionx1-3:~ fusionx1$ terminus cli version
+------------------+----------+
| Key              | Value    |
+------------------+----------+
| Terminus version | 0.12.0   |
| Terminus script  | terminus |
+------------------+----------+

**Comment by fusionx1** [comment]
I wanna thank you for contributing this plugin, this is awesome. I hope it will work on all versions. I would also like to contribute. Thanks

**Comment by bwood** [comment]
Please upgrade your terminus to 0.13.3.  I believe that will fix this error.

**Comment by bwood** [comment]
I read this hastily on my phone on Friday evening and I misunderstood your post slightly.  Supporting earlier versions of terminus is not a priority for our shop and it might not be possible because [libraries keep changing locations with each terminus release](https://github.com/pantheon-systems/terminus/issues/1276).  This issue explains your problem with terminus 0.12.0.  This issue is also the reason I created the `--version` option for this command which indicates the compatible version of terminus. 

That said, if you find a way to dynamically discover terminus classes that makes the plugin "just work" regardless of terminus version, I'll consider a PR.
